"""create deployment table

Revision ID: 45a83a328ad7
Revises: aad80a179d9b
Create Date: 2023-05-03 22:31:27.994017

"""
from alembic import op
import sqlalchemy as sa

from provision.deployment import SerializedDict

# revision identifiers, used by Alembic.
revision = '45a83a328ad7'
down_revision = 'aad80a179d9b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_info', SerializedDict(), nullable=False),
    sa.Column('jitter_results', SerializedDict(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deployment')
    # ### end Alembic commands ###
