"""create client table

Revision ID: aad80a179d9b
Revises: 
Create Date: 2023-05-03 22:11:27.857093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aad80a179d9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=253), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('mac', sa.String(length=17), nullable=True),
    sa.Column('default_menu_item', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname'),
    sa.UniqueConstraint('mac')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    # ### end Alembic commands ###
